import type { Metadata } from "next";
import { IsMobileProvider } from "@/context/IsMobileContext";
import { ScrollProvider } from "@/context/ScrollContext";
import SmoothScroll from "@/context/SmoothScroll";
import Header from "@/components/Navbar"
import Footer from "@/components/Footer";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-white text-black"
      >
        <IsMobileProvider>
          <ScrollProvider>
            <SmoothScroll>
              <Header />
              {children}
              <Footer/>
            </SmoothScroll>
          </ScrollProvider>
        </IsMobileProvider>
      </body>
    </html>
  );
}
