import type { Metadata } from "next";
import { IsMobileProvider } from "../context/IsMobileContext";
import { ScrollProvider } from "@/context/ScrollContext";
import SmoothScroll from "@/context/SmoothScroll";
import Header from "@/components/Navbar"
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <IsMobileProvider>
          <ScrollProvider>
            <SmoothScroll>
              <Header />
              {children}
            </SmoothScroll>
          </ScrollProvider>
        </IsMobileProvider>
      </body>
    </html>
  );
}
